apiVersion: v1
kind: ReplicationController
metadata:
  name: mynginx-rc
spec:
  replicas: 2
  selector:
    app: mynginx
    version: 2.6.2
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
        - name: mynginx
          image: nginx
          ports:
            - containerPort: 80
